async function main() {
  const req = await fetch("http://localhost:3000/api/auth/forget-password", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email: "arontheprofesional@gmail.com", redirectTo: "/reset-password" })
  });
  
  await new Promise(r => setTimeout(r, 1000));
  
  const { developmentResetLinks } = await import("./src/lib/auth.ts");
  const link = developmentResetLinks.get("arontheprofesional@gmail.com");
  
  // The link I stored in my latest update is the FRONTEND URL. 
  // Let's get the original URL generated by Better Auth from the Map if we can, or just look at the console.
  console.log("My stored link:", link);
}

main().catch(console.error);
